import { defineConfig } from "oxlint";

export default defineConfig({
  categories: {
    correctness: "error",
    nursery: "error",
    pedantic: "error",
    perf: "error",
    restriction: "error",
    style: "error",
    suspicious: "error",
  },
  env: { browser: true },
  globals: { chrome: "readonly" },
  ignorePatterns: ["**/fixtures/**"],
  overrides: [
    {
      files: ["build.ts", "scripts/**/*.ts"],
      env: { browser: false, node: true },
      globals: { Bun: "readonly", chrome: "off" },
      rules: {
        "import/no-nodejs-modules": "off",
      },
    },
    {
      files: ["e2e/**/*.ts"],
      env: { browser: true, node: true },
      rules: {
        "import/no-nodejs-modules": "off",
      },
    },
    {
      files: ["**/*.test.ts"],
      globals: { Bun: "readonly" },
    },
    {
      files: ["oxlint.config.ts", "knip.config.ts"],
      env: { browser: false, node: true },
      globals: { chrome: "off" },
      rules: {
        "import/no-default-export": "off",
      },
    },
  ],
  plugins: ["eslint", "typescript", "unicorn", "oxc", "promise", "import"],
  rules: {
    "func-style": ["error", "declaration"],
    "id-length": ["error", { exceptions: ["T", "i", "j", "x", "y", "_"] }],
    "import/consistent-type-specifier-style": "off",
    "import/exports-last": "off",
    "import/group-exports": "off",
    "import/max-dependencies": ["error", { max: 20 }],
    "import/no-named-export": "off",
    "import/prefer-default-export": "off",
    "init-declarations": "off",
    "max-lines-per-function": ["error", { max: 250 }],
    "max-statements": ["error", { max: 60 }],
    "no-await-in-loop": "off",
    "no-console": "off",
    "no-continue": "off",
    "no-inline-comments": "off",
    "no-magic-numbers": "off",
    "no-ternary": "off",
    "no-undefined": "off",
    "oxc/no-async-await": "off",
    "oxc/no-optional-chaining": "off",
    "oxc/no-rest-spread-properties": "off",
    "promise/catch-or-return": "off",
    "promise/prefer-await-to-then": "off",
    "require-await": "off",
    "sort-imports": "off",
    "sort-keys": "off",
    "typescript/no-unnecessary-condition": "off",
    "typescript/prefer-readonly-parameter-types": [
      "error",
      {
        allow: [
          { from: "lib", name: "Element" },
          { from: "lib", name: "HTMLElement" },
          { from: "lib", name: "HTMLButtonElement" },
          { from: "lib", name: "HTMLInputElement" },
          { from: "lib", name: "HTMLTextAreaElement" },
          { from: "lib", name: "HTMLImageElement" },
          { from: "lib", name: "HTMLAnchorElement" },
          { from: "lib", name: "HTMLDivElement" },
          { from: "lib", name: "HTMLProgressElement" },
          { from: "lib", name: "HTMLSpanElement" },
          { from: "lib", name: "File" },
          { from: "lib", name: "Blob" },
          { from: "lib", name: "MediaSource" },
          { from: "lib", name: "MessageEvent" },
          { from: "lib", name: "KeyboardEvent" },
          { from: "lib", name: "MouseEvent" },
          { from: "lib", name: "Event" },
          { from: "lib", name: "PointerEvent" },
          { from: "lib", name: "Promise" },
          { from: "lib", name: "RegExp" },
          { from: "lib", name: "Document" },
          { from: "lib", name: "Node" },
          { from: "lib", name: "MutationObserver" },
          { from: "lib", name: "Date" },
          { from: "lib", name: "Uint8Array" },
          { from: "lib", name: "Record" },
          { from: "package", name: "Page", package: "@playwright/test" },
          { from: "package", name: "BrowserContext", package: "@playwright/test" },
          { from: "package", name: "Worker", package: "@playwright/test" },
          { from: "package", name: "Route", package: "@playwright/test" },
          { from: "package", name: "ConsoleMessage", package: "@playwright/test" },
          { from: "package", name: "MessageSender", package: "@types/chrome" },
        ],
        ignoreInferredTypes: true,
        treatMethodsAsReadonly: true,
      },
    ],
    "typescript/promise-function-async": "off",
    "typescript/require-await": "off",
    "typescript/strict-void-return": "off",
  },
});
